@baseUrl = http://localhost:3002

###
# -------------------------
POST {{baseUrl}}/generate

{
  "node_types": [0, 1, 2, 2, 3, 3, 3, 4, 14],
  "edges":  [[0, 2], [0, 1], [0, 3], [0, 6], [0, 8], [2, 4], [2, 7], [3, 5]],
  "scale": [3,3]
}

